/**
 * Maps common country names (lowercase) to ISO 3166-1 alpha-3 codes
 * used by react-simple-maps / Natural Earth TopoJSON.
 * Extend as needed for your user base.
 */
const COUNTRY_TO_ISO3 = {
  afghanistan: 'AFG',
  albania: 'ALB',
  algeria: 'DZA',
  argentina: 'ARG',
  australia: 'AUS',
  austria: 'AUT',
  bahrain: 'BHR',
  bangladesh: 'BGD',
  belgium: 'BEL',
  bhutan: 'BTN',
  brazil: 'BRA',
  canada: 'CAN',
  chile: 'CHL',
  china: 'CHN',
  colombia: 'COL',
  'czech republic': 'CZE',
  czechia: 'CZE',
  denmark: 'DNK',
  egypt: 'EGY',
  ethiopia: 'ETH',
  finland: 'FIN',
  france: 'FRA',
  germany: 'DEU',
  ghana: 'GHA',
  greece: 'GRC',
  hungary: 'HUN',
  iceland: 'ISL',
  india: 'IND',
  indonesia: 'IDN',
  iran: 'IRN',
  iraq: 'IRQ',
  ireland: 'IRL',
  israel: 'ISR',
  italy: 'ITA',
  japan: 'JPN',
  jordan: 'JOR',
  kenya: 'KEN',
  kuwait: 'KWT',
  lebanon: 'LBN',
  malaysia: 'MYS',
  maldives: 'MDV',
  mexico: 'MEX',
  morocco: 'MAR',
  myanmar: 'MMR',
  nepal: 'NPL',
  netherlands: 'NLD',
  'new zealand': 'NZL',
  nigeria: 'NGA',
  norway: 'NOR',
  oman: 'OMN',
  pakistan: 'PAK',
  peru: 'PER',
  philippines: 'PHL',
  poland: 'POL',
  portugal: 'PRT',
  qatar: 'QAT',
  romania: 'ROU',
  russia: 'RUS',
  'saudi arabia': 'SAU',
  singapore: 'SGP',
  'south africa': 'ZAF',
  'south korea': 'KOR',
  spain: 'ESP',
  'sri lanka': 'LKA',
  sweden: 'SWE',
  switzerland: 'CHE',
  taiwan: 'TWN',
  tanzania: 'TZA',
  thailand: 'THA',
  turkey: 'TUR',
  uae: 'ARE',
  'united arab emirates': 'ARE',
  uk: 'GBR',
  'united kingdom': 'GBR',
  usa: 'USA',
  'united states': 'USA',
  'united states of america': 'USA',
  vietnam: 'VNM',
}

/**
 * Resolve a free-text country name to an ISO alpha-3 code.
 * Returns undefined if no mapping is found.
 */
export function countryNameToISO3(name) {
  if (!name) return undefined
  return COUNTRY_TO_ISO3[name.trim().toLowerCase()]
}
